// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc_create_user.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9032256a706c222, []int{0}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9032256a706c222, []int{1}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "pb.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "pb.CreateUserResponse")
}

func init() {
	proto.RegisterFile("rpc_create_user.proto", fileDescriptor_a9032256a706c222)
}

var fileDescriptor_a9032256a706c222 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x31, 0x4b, 0xc5, 0x30,
	0x14, 0x85, 0x79, 0xcf, 0x2a, 0xed, 0x75, 0x32, 0x28, 0x94, 0x2a, 0xa8, 0x9d, 0x9c, 0x52, 0xa8,
	0xff, 0x40, 0x77, 0x87, 0x82, 0x8b, 0x4b, 0x49, 0xda, 0xab, 0x16, 0x93, 0xe6, 0x9a, 0x9b, 0xe0,
	0xe6, 0x6f, 0x97, 0xa4, 0xa8, 0x6f, 0xfc, 0xce, 0x77, 0x92, 0xc3, 0x85, 0x0b, 0x4f, 0xd3, 0x38,
	0x79, 0x54, 0x01, 0xc7, 0xc8, 0xe8, 0x25, 0x79, 0x17, 0x9c, 0xd8, 0x93, 0x6e, 0xe0, 0x9f, 0xdb,
	0x6f, 0x38, 0x7b, 0xcc, 0xa5, 0x67, 0x46, 0x3f, 0xe0, 0x67, 0x44, 0x0e, 0xa2, 0x81, 0x32, 0x55,
	0x56, 0x65, 0xb1, 0xde, 0xdd, 0xec, 0xee, 0xaa, 0xe1, 0x8f, 0xc5, 0x25, 0x54, 0xaf, 0xd1, 0x98,
	0x31, 0xcb, 0xfd, 0x26, 0x53, 0xf0, 0x94, 0xe4, 0x39, 0x1c, 0xa3, 0x55, 0x8b, 0xa9, 0x8f, 0xb2,
	0xd8, 0x20, 0x7d, 0x47, 0x8a, 0xf9, 0xcb, 0xf9, 0xb9, 0x2e, 0xb6, 0x17, 0xbf, 0xdc, 0xf6, 0x20,
	0x0e, 0xf7, 0x99, 0xdc, 0xca, 0x28, 0xae, 0xa0, 0x48, 0x83, 0x79, 0xfc, 0xb4, 0x2f, 0x25, 0x69,
	0x99, 0x7d, 0x4e, 0x1f, 0x6e, 0x5f, 0xae, 0xdf, 0x96, 0xf0, 0x1e, 0xb5, 0x9c, 0x9c, 0xed, 0x66,
	0xc5, 0x2e, 0xcc, 0x1d, 0x2f, 0x96, 0x0c, 0x6a, 0xb5, 0x7e, 0x74, 0xa4, 0xf5, 0x49, 0xbe, 0xee,
	0xfe, 0x27, 0x00, 0x00, 0xff, 0xff, 0xfc, 0xaa, 0x7f, 0x97, 0x06, 0x01, 0x00, 0x00,
}
