// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc_verify_email.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VerifyEmailRequest struct {
	EmailId              int64    `protobuf:"varint,1,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	SecretCode           string   `protobuf:"bytes,2,opt,name=secret_code,json=secretCode,proto3" json:"secret_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyEmailRequest) Reset()         { *m = VerifyEmailRequest{} }
func (m *VerifyEmailRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyEmailRequest) ProtoMessage()    {}
func (*VerifyEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_422f75ae3a343f23, []int{0}
}

func (m *VerifyEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyEmailRequest.Unmarshal(m, b)
}
func (m *VerifyEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyEmailRequest.Marshal(b, m, deterministic)
}
func (m *VerifyEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyEmailRequest.Merge(m, src)
}
func (m *VerifyEmailRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyEmailRequest.Size(m)
}
func (m *VerifyEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyEmailRequest proto.InternalMessageInfo

func (m *VerifyEmailRequest) GetEmailId() int64 {
	if m != nil {
		return m.EmailId
	}
	return 0
}

func (m *VerifyEmailRequest) GetSecretCode() string {
	if m != nil {
		return m.SecretCode
	}
	return ""
}

type VerifyEmailResponse struct {
	IsVerified           bool     `protobuf:"varint,1,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyEmailResponse) Reset()         { *m = VerifyEmailResponse{} }
func (m *VerifyEmailResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyEmailResponse) ProtoMessage()    {}
func (*VerifyEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_422f75ae3a343f23, []int{1}
}

func (m *VerifyEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyEmailResponse.Unmarshal(m, b)
}
func (m *VerifyEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyEmailResponse.Marshal(b, m, deterministic)
}
func (m *VerifyEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyEmailResponse.Merge(m, src)
}
func (m *VerifyEmailResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyEmailResponse.Size(m)
}
func (m *VerifyEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyEmailResponse proto.InternalMessageInfo

func (m *VerifyEmailResponse) GetIsVerified() bool {
	if m != nil {
		return m.IsVerified
	}
	return false
}

func init() {
	proto.RegisterType((*VerifyEmailRequest)(nil), "pb.VerifyEmailRequest")
	proto.RegisterType((*VerifyEmailResponse)(nil), "pb.VerifyEmailResponse")
}

func init() {
	proto.RegisterFile("rpc_verify_email.proto", fileDescriptor_422f75ae3a343f23)
}

var fileDescriptor_422f75ae3a343f23 = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x2a, 0x48, 0x8e,
	0x2f, 0x4b, 0x2d, 0xca, 0x4c, 0xab, 0x8c, 0x4f, 0xcd, 0x4d, 0xcc, 0xcc, 0xd1, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x0a, 0xe0, 0x12, 0x0a, 0x03, 0xcb, 0xb8, 0x82, 0x24,
	0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x24, 0xb9, 0x38, 0xc0, 0x0a, 0xe3, 0x33, 0x53,
	0x24, 0x18, 0x15, 0x18, 0x35, 0x98, 0x83, 0xd8, 0xc1, 0x7c, 0xcf, 0x14, 0x21, 0x79, 0x2e, 0xee,
	0xe2, 0xd4, 0xe4, 0xa2, 0xd4, 0x92, 0xf8, 0xe4, 0xfc, 0x94, 0x54, 0x09, 0x26, 0x05, 0x46, 0x0d,
	0xce, 0x20, 0x2e, 0x88, 0x90, 0x73, 0x7e, 0x4a, 0xaa, 0x92, 0x19, 0x97, 0x30, 0x8a, 0x89, 0xc5,
	0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x20, 0x7d, 0x99, 0xc5, 0x10, 0x57, 0x64, 0xa6, 0x42, 0x4c, 0xe5,
	0x08, 0xe2, 0xca, 0x2c, 0x0e, 0x83, 0x8a, 0x38, 0x29, 0x46, 0xc9, 0xa7, 0x67, 0x96, 0x64, 0x94,
	0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0xa7, 0x24, 0x16, 0xe7, 0x97, 0xa4, 0xe8, 0x17, 0x67, 0xe6,
	0x16, 0xe4, 0xa4, 0x26, 0x25, 0xe6, 0x65, 0xeb, 0x17, 0x24, 0x25, 0xb1, 0x81, 0xdd, 0x6d, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x08, 0x48, 0x5a, 0xb1, 0xd1, 0x00, 0x00, 0x00,
}
